name: Build ACNHPokerCore

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    
    runs-on: windows-latest
    
    steps:
    - name: 签出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 安装 .NET SDK 9.0.13
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.13'  # 指定与您的运行时完全匹配的SDK版本

    - name: 显示 .NET 信息
      run: dotnet --info

    - name: 还原依赖
      run: dotnet restore ACNHPokerCore.sln

    - name: 构建 ${{ matrix.configuration }}
      run: dotnet build ACNHPokerCore.sln --configuration ${{ matrix.configuration }} --no-restore -nowarn:CS4014,CS1998

    - name: 执行单元测试
      run: dotnet test ACNHPokerCore.sln --configuration ${{ matrix.configuration }} --no-build --verbosity normal
      continue-on-error: true

    - name: 上传构建工件
      uses: actions/upload-artifact@v4
      with:
        name: ACNHPokerCore-${{ matrix.configuration }}
        path: |
          ACNHPokerCore/bin/${{ matrix.configuration }}/
          **/bin/${{ matrix.configuration }}/
        if-no-files-found: warn
